version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies..."
      - npm install
  build:
    commands:
      - echo "Build phase - nothing extra needed for this simple app"
artifacts:
  files:
    - '**/*'
  base-directory: '.'